# Generated by Django 6.0.2 on 2026-02-12 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('model_type', models.CharField(choices=[('property_predictor', 'Property Predictor'), ('structure_generator', 'Structure Generator'), ('formulation_optimizer', 'Formulation Optimizer'), ('experiment_designer', 'Experiment Designer')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text="{'r2': 0.85, 'rmse': 0.12}")),
                ('training_data_count', models.IntegerField(default=0)),
                ('model_path', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField(default=1, help_text='Iteration number in evolutionary optimization')),
                ('smiles', models.TextField()),
                ('predicted_properties', models.JSONField(default=dict)),
                ('efficacy_score', models.FloatField(blank=True, null=True)),
                ('stability_score', models.FloatField(blank=True, null=True)),
                ('safety_score', models.FloatField(blank=True, null=True)),
                ('pareto_rank', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('selected', 'Selected'), ('synthesized', 'Synthesized'), ('tested', 'Tested'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='ai_models.aimodel')),
            ],
            options={
                'ordering': ['pareto_rank', '-efficacy_score'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(help_text='Model input features')),
                ('output_data', models.JSONField(help_text='Predicted values')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ai_models.aimodel')),
                ('formulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='formulations.lnpformulation')),
            ],
        ),
    ]
