# Generated by Django 6.0.2 on 2026-02-12 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(choices=[('liquid_handler', 'Liquid Handler'), ('microfluidic', 'Microfluidic Mixer'), ('dls', 'Dynamic Light Scattering'), ('plate_reader', 'Plate Reader'), ('hplc', 'HPLC'), ('centrifuge', 'Centrifuge')], max_length=30)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=200)),
                ('model_number', models.CharField(blank=True, default='', max_length=200)),
                ('protocol', models.CharField(choices=[('rest_api', 'REST API'), ('mqtt', 'MQTT'), ('opcua', 'OPC-UA'), ('serial', 'Serial'), ('manual', 'Manual')], default='rest_api', max_length=20)),
                ('endpoint_url', models.CharField(blank=True, default='', max_length=500)),
                ('api_key', models.CharField(blank=True, default='', max_length=500)),
                ('is_connected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('error', 'Error'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Temperature, humidity, etc.')),
                ('message', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='equipment.equipment')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
