# Generated by Django 6.0.2 on 2026-02-12 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cholesterol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('smiles', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='HeadGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('smiles', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HelperLipid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('smiles', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Linker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('smiles', models.TextField(blank=True, default='')),
                ('linker_type', models.CharField(choices=[('ester', 'Ester'), ('carbonate', 'Carbonate'), ('disulfide', 'Disulfide'), ('amide', 'Amide'), ('ether', 'Ether'), ('other', 'Other')], default='other', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PEGLipid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('smiles', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('smiles', models.TextField(blank=True, default='')),
                ('carbon_count', models.IntegerField(blank=True, null=True)),
                ('is_branched', models.BooleanField(default=False)),
                ('has_unsaturation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IonizableLipid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('smiles', models.TextField(db_index=True)),
                ('protonated_smiles', models.TextField(blank=True, default='')),
                ('molecular_weight', models.FloatField(blank=True, db_index=True, null=True)),
                ('logp', models.FloatField(blank=True, db_index=True, null=True)),
                ('tpsa', models.FloatField(blank=True, help_text='Topological Polar Surface Area', null=True)),
                ('heavy_atoms', models.IntegerField(blank=True, null=True)),
                ('rings', models.IntegerField(blank=True, null=True)),
                ('aromatic_rings', models.IntegerField(blank=True, null=True)),
                ('rotatable_bonds', models.IntegerField(blank=True, null=True)),
                ('vdw_volume', models.FloatField(blank=True, help_text='van der Waals Volume', null=True)),
                ('hbd', models.IntegerField(blank=True, help_text='H-Bond Donors', null=True)),
                ('hba', models.IntegerField(blank=True, help_text='H-Bond Acceptors', null=True)),
                ('molar_refractivity', models.FloatField(blank=True, null=True)),
                ('fsp3', models.FloatField(blank=True, help_text='Fraction sp3 Carbons', null=True)),
                ('sp3_carbons', models.IntegerField(blank=True, null=True)),
                ('nitrogen_count', models.IntegerField(blank=True, null=True)),
                ('has_ester', models.BooleanField(default=False)),
                ('has_carbonate', models.BooleanField(default=False)),
                ('has_disulfide', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('lnpdb', 'LNPDB'), ('literature', 'Literature'), ('generated', 'AI Generated'), ('synthesized', 'Synthesized')], default='lnpdb', max_length=20)),
                ('publication_link', models.URLField(blank=True, default='')),
                ('publication_pmid', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lipids', to='compounds.headgroup')),
                ('linker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lipids', to='compounds.linker')),
                ('tail1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lipids_tail1', to='compounds.tail')),
                ('tail2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lipids_tail2', to='compounds.tail')),
                ('tail3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lipids_tail3', to='compounds.tail')),
                ('tail4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lipids_tail4', to='compounds.tail')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['molecular_weight', 'logp'], name='compounds_i_molecul_bfc674_idx'), models.Index(fields=['has_ester', 'has_carbonate', 'has_disulfide'], name='compounds_i_has_est_025b8d_idx')],
            },
        ),
    ]
