# Generated by Django 5.1 on 2026-02-15 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0003_workflowrun_report_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('solvent', 'Solvent'), ('buffer', 'Buffer'), ('lipid_stock', 'Lipid Stock'), ('mrna_cargo', 'mRNA Cargo'), ('consumable', 'Consumable'), ('reagent', 'Reagent')], max_length=20)),
                ('cas_number', models.CharField(blank=True, default='', max_length=50)),
                ('unit', models.CharField(choices=[('mL', 'mL'), ('L', 'L'), ('mg', 'mg'), ('g', 'g'), ('ug', 'µg'), ('units', 'units')], max_length=10)),
                ('storage_conditions', models.CharField(blank=True, default='', max_length=100)),
                ('minimum_stock', models.FloatField(default=0, help_text='Low-stock alert threshold')),
                ('reorder_point', models.FloatField(default=0, help_text='Reorder trigger quantity')),
                ('pipeline_steps', models.JSONField(blank=True, default=list, help_text='e.g. ["synthesize","formulate"]')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Supplier, purity, catalog no., etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReagentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100)),
                ('quantity', models.FloatField(help_text='Current remaining quantity')),
                ('initial_quantity', models.FloatField(help_text='Quantity when received')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.reagent')),
            ],
            options={
                'ordering': ['expiry_date', 'received_at'],
            },
        ),
        migrations.CreateModel(
            name='ReagentConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField()),
                ('batch_id', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.reagent')),
                ('workflow_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagent_consumptions', to='workflow.workflowstep')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions', to='inventory.reagentstock')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
