# Generated by Django 5.1 on 2026-02-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrun',
            name='status',
            field=models.CharField(choices=[('designing', 'Designing'), ('queued', 'Queued'), ('running', 'Running'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='designing', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('awaiting_approval', 'Awaiting Approval')], default='pending', max_length=20),
        ),
    ]
