# Generated by Django 5.1 on 2026-02-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_workflowrun_status_alter_workflowstep_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='report_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
