# Generated by Django 6.0.2 on 2026-02-12 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LNPFormulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulation_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('il_molratio', models.FloatField(help_text='Ionizable lipid molar ratio')),
                ('hl_molratio', models.FloatField(blank=True, null=True)),
                ('chl_molratio', models.FloatField(blank=True, null=True)),
                ('peg_molratio', models.FloatField(blank=True, null=True)),
                ('fifth_component_name', models.CharField(blank=True, default='', max_length=200)),
                ('fifth_component_smiles', models.TextField(blank=True, default='')),
                ('fifth_component_molratio', models.FloatField(blank=True, null=True)),
                ('il_to_na_massratio', models.FloatField(blank=True, help_text='IL:nucleic acid mass ratio', null=True)),
                ('il_to_na_chargeratio', models.FloatField(blank=True, help_text='IL:nucleic acid charge ratio (N/P)', null=True)),
                ('mixing_method', models.CharField(choices=[('microfluidics', 'Microfluidics'), ('handmixed', 'Hand Mixed')], default='microfluidics', max_length=20)),
                ('aqueous_buffer', models.CharField(blank=True, default='', max_length=200)),
                ('dialysis_buffer', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(choices=[('lnpdb', 'LNPDB'), ('designed', 'AI Designed'), ('manual', 'Manual')], default='lnpdb', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cholesterol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulations', to='compounds.cholesterol')),
                ('helper_lipid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulations', to='compounds.helperlipid')),
                ('ionizable_lipid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulations', to='compounds.ionizablelipid')),
                ('peg_lipid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulations', to='compounds.peglipid')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
